"""empty message

Revision ID: 53b421fc2c03
Revises: 2b3a648496b4
Create Date: 2022-05-31 15:58:21.308423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53b421fc2c03'
down_revision = '2b3a648496b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_people')
    op.drop_index('name', table_name='planet')
    op.drop_index('name_2', table_name='planet')
    op.drop_table('planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('diameter', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('climate', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('terrain', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('population', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('inhabitants', mysql.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name_2', 'planet', ['name'], unique=False)
    op.create_index('name', 'planet', ['name'], unique=False)
    op.create_table('fav_people',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('people_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], name='fav_people_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fav_people_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
